// Generated by CoffeeScript 1.3.3
(function() {

  $(window).ready(function() {
    window.Draw = {
      init: function() {
        this.view = $('#canvas_view');
        this.view_context = this.view[0].getContext("2d");
        this.background = $('#canvas_background');
        this.background_context = this.background[0].getContext("2d");
        this.use_view();
        return this.images = {};
      },
      use_background: function() {
        return this.context = this.background_context;
      },
      use_view: function() {
        return this.context = this.view_context;
      },
      add_image: function(name, url) {
        var img;
        img = new Image();
        img.src = url;
        $(img).attr('name', name);
        return $(img).imagesLoaded(function() {
          name = this.attr('name');
          if (!window.Draw.images[name]) {
            return window.Draw.images[name] = this[0];
          }
        });
      },
      image: function(imgname, x, y) {
        if (this.images[imgname]) {
          return this.context.drawImage(this.images[imgname], x, y);
        }
      },
      draw_box: function(x, y, w, h, options) {
        if (x == null) {
          x = 0;
        }
        if (y == null) {
          y = 0;
        }
        if (w == null) {
          w = 100;
        }
        if (h == null) {
          h = 100;
        }
        if (options == null) {
          options = {
            fillStyle: "transparent",
            strokeStyle: "rgb(113, 183, 248)",
            lineWidth: 1
          };
        }
        x += .5;
        y += .5;
        this.context.fillStyle = options.fillStyle;
        this.context.strokeStyle = options.strokeStyle;
        this.context.lineWidth = options.lineWidth;
        this.context.beginPath();
        this.context.moveTo(x, y);
        this.context.lineTo(x + w, y);
        this.context.lineTo(x + w, y + h);
        this.context.lineTo(x, y + h);
        this.context.lineTo(x, y);
        this.context.closePath();
        this.context.fill();
        if (options.lineWidth > 0) {
          return this.context.stroke();
        }
      },
      draw_line: function(x, y, x2, y2, options) {
        if (x == null) {
          x = 0;
        }
        if (y == null) {
          y = 0;
        }
        if (x2 == null) {
          x2 = 0;
        }
        if (y2 == null) {
          y2 = 0;
        }
        if (options == null) {
          options = {
            fillStyle: "transparent",
            strokeStyle: "rgb(113, 183, 248)",
            lineWidth: 1
          };
        }
        x += .5;
        y += .5;
        x2 += .5;
        y2 += .5;
        this.context.fillStyle = options.fillStyle;
        this.context.strokeStyle = options.strokeStyle;
        if (options.lineWidth) {
          this.context.lineWidth = options.lineWidth;
        }
        this.context.beginPath();
        this.context.moveTo(x, y);
        this.context.lineTo(x2, y2);
        this.context.closePath();
        return this.context.stroke();
      }
    };
    return window.Draw.init();
  });

}).call(this);
