// Generated by CoffeeScript 1.3.3
(function() {

  $(window).load(function() {
    window.Terrain = {
      init: function() {
        this.width = window.Map.width;
        this.height = window.Map.height;
        this.tilesize = window.Map.tilesize;
        this.perlin = new PERLIN.Generator();
        this.perlin.octaves = 6;
        return this.perlin.frequency = .04;
      },
      draw_terrain: function() {
        console.log("terrain drawing");
        window.Draw.use_layer('background');
        this.perlin.generate([0, 0], [this.width, this.height], function(point, value) {
          var rot, sx, sy;
          sx = (point[0] + parseInt(point[0] / 16) + parseInt(point[1] / 8)) % 8;
          sy = 7 - (point[1] + parseInt(point[1] / 16)) % 8;
          window.Draw.context.globalAlpha = 1.0;
          rot = false;
          if (Math.random() < .1) {
            rot = (Math.PI / 2) * (parseInt(point[0] / 8) % 4);
          }
          window.Draw.sub_image('terrain3', point[0] * 32, point[1] * 32, 32, 32, 32, [sx, sy], rot);
          sx = (point[0] + parseInt(point[0] / 8)) % 4;
          sy = (point[1] + parseInt(point[1] / 8)) % 4;
          window.Draw.context.globalAlpha = value;
          return window.Draw.sub_image('terrain2', point[0] * 32, point[1] * 32, 32, 32, 32, [sx, sy], Math.pi / 4 * (point[0] / 16) % 4);
        });
        this.perlin.octaves = 8;
        this.perlin.frequency = .02;
        return this.perlin.generate([0, 0], [this.width, this.height], function(point, value) {
          var sx, sy;
          if (value > .5) {
            window.Draw.use_layer('background');
            sx = point[0] % 16;
            sy = point[1] % 16;
            window.Draw.context.globalAlpha = (value - .5) * 2;
            return window.Draw.sub_image('terrain', point[0] * 32, point[1] * 32, 32, 32, 16, [sx, sy]);
          }
        });
      }
    };
    return window.Terrain.init();
  });

}).call(this);
